version: '{build}'

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - cmd: ver
  - cmd: mvn --version
  - cmd: java -version
  - cmd: git checkout -

build_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

test_script:
  - mvn test -B
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report -DserviceName=appveyor-ci -DserviceJobId='{build}'

cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
